--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  creationTimestamp: ~
  labels: 
    app: process
  name: process
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: process
  strategy: {}
  template: 
    metadata: 
      creationTimestamp: ~
      labels: 
        app: process
    spec: 
      containers: 
        - 
          env:
           - name: spring.datasource.url
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_DATASOURCE_URL_DEV_PROCESS
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_DATASOURCE_USER
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_DATASOURCE_PASSWD
            - name: spring.data.elasticsearch.client.reactive.endpoints
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS
            - name: spring.elasticsearch.rest.uris
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_ELASTICSEARCH_REST_URIS
            - name: mdo.config.jwt_rsk
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MDO_CONFIG_JWT_RSK
            - name: spring.rabbitmq.username
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_USER
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_PASSWD
            - name: spring.rabbitmq.addresses
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_ADDRESS
            - name: spring.rabbitmq.host
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_HOST
            - name: spring.rabbitmq.port
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_PORT
            - name: server.canonical.url
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SERVER_CANONICAL_URL_IN_PROCESS
            - name: server.name
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SERVER_NAME
            - name: management.endpoint.health.show-details
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS
            - name: management.endpoint.health.show-details
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS
            - name: management.health.defaults.enabled
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_HEALTH_DEFAULTS_ENABLED
            - name: spring.rabbitmq.ssl.enabled
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_SSL_ENABLED
            - name: grpc.server.port
              value: '10000'
            - name: grpc.core.ui.server.port
              value: '10000'
            - name: server.rest-uri
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: REST_URI
            - name: grpc.core.ui.server.url
              value: "null"
            - name: elastic.link
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: ELASTIC_LINK
            - name: elastic.username
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: ELASTIC_USERNAME
            - name: elastic.password
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: ELASTIC_PASSWORD
            - name: spring.jpa.properties.hibernate.multiTenancy
              value: ' SCHEMA'
            - name: spring.jpa.properties.hibernate.tenant_identifier_resolver
              value: CurrentTenantIdentifierResolver
            - name: spring.jpa.properties.hibernate.multi_tenant_connection_provider
              value: AbstractMultiTenantConnectionProvider
            - name: spring.datasource.driverClassName
              value: org.postgresql.Driver
            - name: spring.datasource.driverClassName
              value: org.postgresql.Driver
            - name: keyCloakUrl
              value: 'https://keycloak-dev.apps.rosa-sg.3xbl.p1.openshiftapps.com/auth'
            - name: keyCloakClientId
              value: 'business-central '
            - name: keyCloakGrantType
              value: password
            - name: keyCloakRealmValue
              value: mdorealm-dev
            - name: keyCloakClientSecret
              value: FT9ZQ0jEgbeAxCuPNvbVcehjpNwq1wDK
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SERVER_CANONICAL_URL_IN_PROCESS
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: NEWRELIC_LICENSE_KEY
            - name: server.kie-uri
              value: >-
                http://svc-drools-bc-kie-x2.dev.svc.cluster.local:8080/kie-server/services/rest/server
            - name: baseUrl
              value: 'http://svc-drools-bc-kie-x2.dev.svc.cluster.local:8080/'
            - name: server.password
              value: wbadmin
            - name: server.username
              value: wbadmin
            - name: grpc.profile.server.url
              value: "null"
            - name: grpc.profile.server.port
              value: '10000'
            - name: management.health.default-enabled
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_HEALTH_DEFAULTS_ENABLED
            - name: management.endpoint.health.group.alb.include
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_ENDPOINT_HEALTH_GROUP_ALB_INCLUDE
            - name: management.endpoint.health.group.alb.show-components
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_ENDPOINT_HEALTH_GROUP_ALB_SHOW-COMPONENTS
            - name: management.endpoint.health.group.alb.show-details
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_ENDPOINT_HEALTH_GROUP_ALB_SHOW-DETAILS
            - name: management.health.group.alb.defaults.enabled
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_HEALTH_GROUP_ALB_DEFAULTS_ENABLED
            - name: grpc.rule.server.url
              value: "null"
            - name: grpc.rule.server.port
              value: '10000'
            - name: spring.jpa.properties.hibernate.cache.use_second_level_cache
              value: 'true'
            - name: spring.jpa.properties.javax.persistence.sharedCache.mode
              value: ENABLE_SELECTIVE
            - name: spring.jpa.properties.hibernate.cache.use_query_cache
              value: 'true'
            - name: spring.jpa.properties.hibernate.cache.region.factory_class
              value: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            - name: spring.jpa.properties.hibernate.generate_statistics
              value: 'true'
            - name: grpc.sapws.server.port
              value: '10000'
            - name: grpc.sapws.server.url
              value: "null"
            - name: grpc.intg.server.port
              value: '10000'
            - name: grpc.intg.server.url
              value: "null"
            - name: drool.git.endpoint
              value: dev.masterdataonline.com/business-central/git/
            - name: git.org.name
              value: connekthub-qa
            - name: git.token
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: GIT_TOKEN
            - name: server.max-http-header-size
              value: 512KB
            - name: spring.mvc.pathmatch.matching-strategy
              value: ant-path-matcher
            - name: spring.datasource.hikari.connection-timeout
              value: '20000'
            - name: spring.datasource.hikari.minimum-idle
              value: '1'
            - name: spring.datasource.hikari.maximum-pool-size
              value: '20'
            - name: spring.datasource.hikari.idleTimeout
              value: '30000'
            - name: elastic.protocol
              value: https
            - name: elastic.port
              value: '9200'
            - name: githubType
              value: connekthub-qa
            - name: server.connekthub-qa.token
              value: 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
          securityContext:
            privileged: false
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: "docker.prospecta.com/prospecta/mdo-process:development"
          name: process
          ports:
            - name: spring-port
              containerPort: 8080
              protocol: TCP
            - name: grpc-port
              containerPort: 10000
              protocol: TCP
          resources: {}
      securityContext: {}
      imagePullSecrets:
        - name: nexus-image-pull
---
