---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: core-crud
  name: core-crud
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: core-crud
---
