---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: list
  name: list
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: list
---
